<?php

function misc_menu() {
  $items = array();

  $items['misc/province/cities/%'] = array(
    'title' => 'Misc Get Province Cities',
    'type' => MENU_CALLBACK,
    'page callback' => '_get_province_cities_js',
    'page arguments' => array(3),
    'access callback' => TRUE,
  );
  
  $items['node/%node/subscribe'] = array(
  	'page callback' => 'ride_subscribe',
  	'page arguments' => array(1),
  	'access callback' => TRUE,
  	'type' => MENU_CALLBACK
  );
  
  $items['node/%ctools_js/%node/subscribtion/update/%'] = array(
  	'page callback' => 'ride_subscribtion_update',
    'page arguments' => array(1, 2, 5),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Menu call back to subscribe user for certain ride
 * it initiate in awaiting response status
 * @param $node the ride to subscribe to
 */
function ride_subscribe($node) {
	global $user;
	
	$subscribtion = new stdClass();
	$subscribtion->type = 'ride_subscription';
	
	node_object_prepare($subscribtion);
	
	$subscribtion->title = 'Ride Subscribtion';
	$subscribtion->field_ride = array('und' => array(array('nid' => $node->nid)));
	$subscribtion->field_status = array('und' => array(array('value' => 0)));
	
	node_save($subscribtion);
	
	drupal_goto('node/' . $node->nid);
}


/**
 * Ajax callback that will update update ride subscribtion status with acceptance or rejections
 * @param $node subscribtion to update
 * @param $status	 the new subscribtion status
 */
function ride_subscribtion_update($js = FALSE, $node, $status) {
	$node->field_status['und'][0]['value'] = $status;
	node_save($node);
	
	// if subscribtion was accepted, then the remaining seats is -1
	if ($status == 1) {
		$ride_nid = $node->field_ride['und'][0]['nid'];
		update_passenger_count($ride_nid, -1);
	}
	
	
	
	$message = t('Your response has been saved');
	
	if ($js) {
		$commands = array();
		$commands[] = ajax_command_alert($message);
		$commands[] = ajax_command_remove('.row-' . $node->nid);
		print ajax_render($commands);
		exit;
	}
	else {
		drupal_set_message($message);
		drupal_goto('manage/subscribtions');
	}
}

function update_passenger_count($ride_nid, $count_change) {
	$ride = node_load($ride_nid);
	
	$ride->field_remaining_seats['und'][0]['value'] += $count_change;
	
	node_save($ride);	
}

/**
 * Implments hook_init
 */
function misc_init() {
	
	if (drupal_is_front_page()) {
		//show_homepage_notifications();
	}
	// ajax menu commands, surely there are other ways to fire this action
	// by other triggers
	ctools_add_js('ajax-responder');
	drupal_add_library('system', 'drupal.ajax');	
	
  if (drupal_is_front_page() || $_GET['q'] === 'home') {
    drupal_add_js("jQuery('#block-system-main').prepend('<h1>" . t('Homepage') . "</h1>');", 
      array('type' => 'inline', 'scope' => 'footer', 'group' => JS_THEME));
  }

  $css_file_path = drupal_get_path('module', 'misc') . '/css/misc.css';
  drupal_add_css($css_file_path, array('group' => CSS_DEFAULT, 'every_page' => TRUE));

  $js_file_path = drupal_get_path('module', 'misc') . '/js/misc.js';
  drupal_add_js($js_file_path, array('group' => JS_THEME));

}


/**
 * Implments hook_block_info
 */
function misc_block_info() {
  $blocks['how_it_works'] = array(
    'info' => t('How it works?'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}


/**
 * Implments hook_block_view
 */
function misc_block_view($delta = '') {
  $block = array();

  switch ($delta) {
  case 'how_it_works':
    $block['subject'] = t('How it works?');
    $block['content'] = theme('how_it_works', array('HTML' => NULL));
    break;
  }

  return $block;
}


/**
 * Implements hook_theme().
 */
function misc_theme() {
  return array(
    'how_it_works' => array(
      'template' => 'how_it_works',
      'variables' => array('HTML' => NULL),
    ),
  );
}

function misc_node_view($node, $view_mode, $langcode) {
	switch ($node->type) {
		case 'ride':
			if ($view_mode == 'full') {
				$node->content['apply'] = array(
						'#markup' => ride_apply($node),
						'#weight' => 14
				);
			}		
			break;
	}
}

function ride_apply($node) {
  global $user;
  $items = array();
  // if this the owner user of this ride, show an edit link
  if ($user->uid == $node->uid) {
    $items[] = l(t('Edit'), 'node/' . $node->nid . '/edit');//, 'attributes' => array('class' => array('ride-action'))));
    $items[] = l(t('Delete'), 'node/' . $node->nid . '/delete');
  }

  // not the owner user of this ride
  else {
    // check for subscribtions for this user to this ride
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'ride_subscription')
      ->propertyCondition('uid', $user->uid)
      ->fieldCondition('field_ride', 'nid', $node->nid)
      ->range(0,1);
    $result = $query->execute();

    // there is a subscription ? show status
    if (isset($result['node'])) {
      $nids = array_keys($result['node']);
      $nid = $nids[0];

      $subscribtion = node_load($nid);
      $text = render(field_view_value('node', $subscribtion, 'field_status', $subscribtion->field_status['und'][0]));

      // cancel subscribtion for this ride
      $items[] = $text;
      $items[] = l('Cancel', 'node/' . $nid . '/delete');
    }
    // no subscription ? show link to create one
    else {
      $text = t('Apply');
      $path = 'node/' . $node->nid . '/subscribe';
      $items[] = l(t('Apply'), 'node/' . $node->nid . '/subscribe');
    }
  }

  return theme('item_list', array(
    'items' => $items,
    'attributes' => array('class' => array('ride-action'
  )
)
    )
  );
}



function misc_form_user_register_form_alter(&$form, &$form_state, $form_id) {
	drupal_set_message(t('Please provide correct information about you, so you can be identified by your friends, and you would have a better
	experience using this service.'), 'warning');
	
	$form['#validate'][] = '_misc_user_register_form_validate';
}

function _misc_user_register_form_validate(&$form, &$form_values) {
	if ($form_values['values']['field_country']['und'][0]['value'] == 'EG') {
		if (!isset($form_values['values']['field_ssn']['und'][0]['value']) || 
					strlen($form_values['values']['field_ssn']['und'][0]['value']) < 14) {
			form_set_error('field_ssn', 'social security number must be 14 digits (no spaces)');
		} 
	}
}

/**
 * @author abdelrahman
 * hooks hook_form_FORM_ID_alter
 * ride node add/edit form
 */
function misc_form_ride_node_form_alter(&$form, &$form_state, $form_id) {
	global $user;

	// set default in ride creation to user car information
	if (!is_numeric($form['nid']['#value'])) {
		$user_data = user_load($user->uid);

		try {
			if (isset($user_data->field_car_brand['und'][0]['tid'])) {
				$form['field_car_brand']['und']['#default_value'] = $user_data->field_car_brand['und'][0]['tid'];
			}
			
			if (isset($user_data->field_car_model['und'][0]['value'])) {
				$form['field_car_model']['und'][0]['value']['#default_value'] = $user_data->field_car_model['und'][0]['value'];
			}
			
			if (isset($user_data->field_car_color['und'][0]['jquery_colorpicker'])) {
				$form['field_car_color']['und'][0]['jquery_colorpicker']['#default_value'] = $user_data->field_car_color['und'][0]['jquery_colorpicker'];
			}
		}
		catch (Exception $e) {
			// we do nothing here 
		}
	}
	
  $form['field_cost']['und']['#default_value'] = NULL;
  $form['field_remaining_seats']['#access'] = FALSE;
  
  // making cost mode and cost inline
  $form['field_cost_mode']['#prefix'] = '<div class="container-inline">';
  $form['field_cost']['#suffix'] = '</div>';
  // removing cost lable
  $form['field_cost']['#und'][0]['value']['label'] = '';

  // set ajax call back for from province
  $form['field_from_province']['und']['#ajax'] = array(
    'callback' => '_from_province_changed',
    'wrapper' => 'from_city',
    'effect' => 'fade',
  );

  // set the available options for 'from cities' based on 'from province'
  $form['field_from_city']['#prefix'] = '<div id="from_city">';
  $form['field_from_city']['#suffix'] = '</div>';
  if (isset($form_state['values']['field_from_province']['und'][0]['tid'])) {
    $form['field_from_city']['und']['#options'] = _get_province_cities($form_state['values']['field_from_province']['und'][0]['tid']);
  }
  else {
    $form['field_from_city']['und']['#disabled'] = TRUE;
  }

  // set ajax callback for 'to province'
  $form['field_to_province']['und']['#ajax'] = array(
    'callback' => '_to_province_changed',
    'wrapper' => 'to_city',
    'effect' => 'fade',
  );

  // set avaible options for 'to cities' based on 'to province'
  $form['field_to_city']['#prefix'] = '<div id="to_city">';
  $form['field_to_city']['#suffix'] = '</div>';
  if (isset($form_state['values']['field_to_province']['und'][0]['tid'])) {
    $form['field_to_city']['und']['#options'] = _get_province_cities($form_state['values']['field_to_province']['und'][0]['tid']);
  }
  else {
    $form['field_to_city']['und']['#disabled'] = TRUE;
  }
}


function _from_province_changed($form, $form_state) {
  return $form['field_from_city'];
}

function _to_province_changed($form, $form_state) {
  return $form['field_to_city'];
}

function _get_province_cities($province_tid, $any = '_none') {
  $cities[$any] = '- Select a value -';

  $province = taxonomy_term_load($province_tid);

  if (isset($province->field_cities[und])) {
    foreach ($province->field_cities[und] as $entity) {
      if (isset($entity['tid'])) {
        $city = taxonomy_term_load($entity['tid']);
        if (is_object($city)) {
          $cities[$city->tid] = $city->name;
        }
      }
    }
  }

  return array_reverse($cities, TRUE);
}

function _get_province_cities_js($province_tid) {
  $cities = _get_province_cities($province_tid, 'All');

  drupal_json_output($cities);
  exit;
}

/*
 * Implments hook_node_presave
 */
function misc_node_presave($node) {
	global $user;
	
	switch ($node->type) {
		case 'ride':
			// remaining seats count is the number of available seats
			if ($node->is_new) {
				$node->field_remaining_seats['und'][0]['value'] = $node->field_no_passengers['und'][0]['value'];
			}
			
			$user_data = user_load($user->uid); 
			if (!isset($user_data->field_car_brand['und'][0]['tid'])) {
				$user_data->field_car_brand['und'][0]['tid'] = $node->field_car_brand['und'][0]['tid'];
			}
				
			if (!isset($user_data->field_car_model['und'][0]['value'])) {
				$user_data->field_car_model['und'][0]['value'] = $node->field_car_model['und'][0]['value'];
			}
				
			if (!isset($user_data->field_car_color['und'][0]['jquery_colorpicker'])) {
				$user_data->field_car_color['und'][0]['jquery_colorpicker'] = $node->field_car_color['und'][0]['jquery_colorpicker'];
			}
			
			user_save($user_data);
	}
}

/**
 * Implments hook_node_delete
 * we handle subscribtion delete to increase number of remainging seats
 * @param unknown_type $node
 */
function misc_node_delete($node) {
	if ($node->type == 'ride_subscription') {
	$status = $node->field_status['und'][0]['value'];
	
	// if subscribtion was accepted, then the remaining seats is +1
	// remember this is a deletion
	if ($status == 1) {
		$ride_nid = $node->field_ride['und'][0]['nid'];
		update_passenger_count($ride_nid, 1);
	}
	
	}
}

function misc_node_access($node, $op, $account) {
	if (is_object($node)) {
		switch($node->type) {
			case 'ride':
				if (!$account->uid && $op == 'view' && current_path() != 'search/rides') {
					$msg = t('You have to be logged in to view ride details, Click !here to login',
							array('!here' => l(t('here'), 'user', array('query' => array('destination' => 'node/' . $node->nid)))));
					drupal_set_message($msg, 'warning');
					return NODE_ACCESS_DENY;
				}
		}
	}
	return NODE_ACCESS_IGNORE;
}


function misc_views_pre_view(&$view, &$display_id, &$args) {
	if ($_GET['q'] == 'search/rides' && $view->name == 'search_rides' || $display_id == 'page_1') {
		if (isset($_GET['field_from_province_tid']) &&
				isset($_GET['field_to_province_tid']) &&
				$_GET['field_from_province_tid'] == $_GET['field_to_province_tid']) {
			unset($view->display['attachment_1']);
			unset($view->display['attachment_2']);
			unset($view->display['attachment_3']);
		}
		else {
			$no_from_city = !(isset($_GET['field_from_city_tid']) && is_numeric($_GET['field_from_city_tid']));
			$no_to_city = !(isset($_GET['field_to_city_tid']) && is_numeric($_GET['field_to_city_tid']));
			
			if ($no_to_city) {
				// disabled wider to
				unset($view->display['attachment_1']);
			}
			
			if ($no_from_city) {
				// disable wider from
				unset($view->display['attachment_2']);
			}
			
			if ($no_from_city || $no_to_city) {
				// disable smart search
				unset($view->display['attachment_3']);
			}
		}
	}	
}
